config/routes.rb
Items::Application.routes.draw do
  root :to => "items#index"

  resources :categories
  resources :locations
  resources :items

end

app/helpers/application_helper.rb
module ApplicationHelper
  def html_header
    link_1 = link_to "https://github.com/troywill/rails-ilc", "https://github.com/troywill/rails-ilc"
    link_2 = link_to "http://troywill.com:7000", "http://troywill.com:7000"
    return "#{link_1} | #{link_2}".html_safe
  end
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_name %> <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :item_note %> <%= f.text_field :note %>
  </div>
  <div class="field">
    <label for="item_location_id">Location</label>
  <%= select( "item", "location_id", Location.find(:all, :order => "name" ).collect { |l| [l.name, l.id] } ) %>
  <p>
    <label for="item_categories">Categories</label><br />
  <% for category in Category.find(:all, :order => "name" ) %>
    <%= check_box_tag "item[category_ids][]", category.id, @item.categories.include?(category) %><%= category.name %><br/>
  <% end %>
</p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Name</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.location.name %></td>
    <td><%= item.name %></td>
    <td><%= item.note %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
	<title>Rails Item-Location-Category</title>
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
  </head>
<body>
  <div id='header'>
      <h1><%= html_header %></h1>
  </div>
  <div id='sidebar'>
      <h1>Links</h1>
      <ul>
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "New Item", new_item_path %></li>
	<li><%= link_to "New Location", new_location_path %></li>
	<li><%= link_to "New Category", new_category_path %></li>
      </ul>
  </div>
  <div id='main'>
  <%= yield %>
  </div>
  <div id='footer'>
    <h1><%= Time.now %></h1>
  </div>
  </body>

</html>